version: "2.0"

services:
  web:
    image: piyushch/discord_bot:5.0.0
    env:
      - "TOKEN=YOUR TOKEN HERE"
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 3.0
        memory:
          size: 3Gi
        storage:
          size: 5Gi
  placement:
    westcoast:
      pricing:
        web: 
          denom: uakt
          amount: 5000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
